# Generated by Django 2.0.9 on 2018-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_string', models.CharField(max_length=50, null=True)),
                ('exchange_rate', models.IntegerField()),
                ('raferral_bonus_rate', models.IntegerField(null=True)),
                ('minimum_investment_eth', models.FloatField()),
                ('softcap', models.IntegerField(null=True)),
                ('hardcap', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_type', models.CharField(choices=[('presale', 'Presale'), ('rounda', 'Round-A'), ('roundb', 'Round-B'), ('roundc', 'Round-C')], max_length=10)),
                ('supply', models.IntegerField()),
                ('bonus_rate', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
                ('started_block_height', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolumeBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_bonus_type', models.CharField(choices=[('volumea', 'Volume-A'), ('volumeb', 'Volume-B'), ('volumec', 'Volume-C')], max_length=10)),
                ('amount', models.IntegerField()),
                ('bonus_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('ico', 'Ico'), ('contract', 'Contract'), ('owner', 'Owner')], max_length=254, null=True)),
                ('address', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhitePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kor', 'Kor'), ('eng', 'Eng')], max_length=50)),
                ('file_path', models.FileField(upload_to='whitePaper/')),
            ],
        ),
    ]
