# Generated by Django 2.0.9 on 2018-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoInfos', '0003_auto_20181220_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentinfo',
            name='exchange_rate',
            field=models.FloatField(),
        ),
    ]
