# Generated by Django 2.0.9 on 2018-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoInfos', '0004_auto_20181220_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentinfo',
            name='eth_price',
            field=models.FloatField(null=True),
        ),
    ]
