# Generated by Django 2.0.9 on 2018-12-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoInfos', '0005_investmentinfo_eth_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentinfo',
            old_name='exchange_rate',
            new_name='exchange_price',
        ),
    ]
