# Generated by Django 2.0.9 on 2018-12-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoInfos', '0006_auto_20181220_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('presale', 'Presale'), ('rounda', 'Round-A'), ('roundb', 'Round-B'), ('roundc', 'Round-C'), ('notstartd', 'Not-Started'), ('prerounda', 'Pre-Round-A'), ('preroundb', 'Pre-Round-B'), ('preroundc', 'Pre-Round-C')], max_length=10),
        ),
    ]
