# Generated by Django 2.0.9 on 2018-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoInfos', '0007_auto_20181220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='bonus_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='started_block_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='supply',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
