# Generated by Django 2.0.9 on 2018-12-14 22:26

import bluecots_ico.users.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181215_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_bill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_passport',
        ),
        migrations.AddField(
            model_name='user',
            name='photo_bill_file_name',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=bluecots_ico.users.models.User.photo_file_name),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_passport_file_name',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=bluecots_ico.users.models.User.photo_file_name),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('drive_license', 'Drive License'), ('passport', 'Passport'), ('id_card', 'ID Card')], default='passport', max_length=10),
        ),
    ]
