# Generated by Django 2.0.9 on 2018-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181216_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('country', 'Country'), ('photo', 'Photo'), ('none', 'None'), ('mobile_number', 'Mobile number')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('id_card', 'ID Card'), ('drive_license', 'Drive License'), ('passport', 'Passport')], default='passport', max_length=50),
        ),
    ]
