# Generated by Django 2.0.9 on 2018-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181220_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('photo', 'Photo'), ('mobile_number', 'Mobile number'), ('none', 'None'), ('country', 'Country')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('drive_license', 'Drive License'), ('passport', 'Passport'), ('id_card', 'ID Card')], default='passport', max_length=50),
        ),
    ]
