# Generated by Django 2.0.9 on 2018-12-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181220_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('mobile_number', 'Mobile number'), ('country', 'Country'), ('none', 'None'), ('photo', 'Photo')], default='none', max_length=254, null=True),
        ),
    ]
