# Generated by Django 2.0.9 on 2018-12-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181220_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('country', 'Country'), ('none', 'None'), ('photo', 'Photo'), ('mobile_number', 'Mobile number')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('drive_license', 'Drive License')], default='passport', max_length=50),
        ),
    ]
