# Generated by Django 2.0.9 on 2018-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20181220_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('country', 'Country'), ('none', 'None'), ('mobile_number', 'Mobile number'), ('photo', 'Photo')], default='none', max_length=254, null=True),
        ),
    ]
