# Generated by Django 2.0.9 on 2018-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20181220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('mobile_number', 'Mobile number'), ('country', 'Country'), ('none', 'None'), ('photo', 'Photo')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('drive_license', 'Drive License'), ('id_card', 'ID Card')], default='passport', max_length=50),
        ),
    ]
