# Generated by Django 2.0.9 on 2019-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190109_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('photo', 'Photo'), ('country', 'Country'), ('mobile_number', 'Mobile number'), ('none', 'None')], default='none', max_length=254, null=True),
        ),
    ]
