# Generated by Django 2.0.9 on 2019-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190109_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_string_pw',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
