# Generated by Django 2.0.9 on 2019-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_temp_string_pw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_string_pw',
            new_name='temp_string',
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('country', 'Country'), ('none', 'None'), ('photo', 'Photo'), ('mobile_number', 'Mobile number')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('id_card', 'ID Card'), ('drive_license', 'Drive License'), ('passport', 'Passport')], default='passport', max_length=50),
        ),
    ]
