# Generated by Django 2.0.9 on 2019-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190115_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('photo', 'Photo'), ('country', 'Country'), ('mobile_number', 'Mobile number'), ('none', 'None')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('approving', 'Approving'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('drive_license', 'Drive License'), ('passport', 'Passport'), ('id_card', 'ID Card')], default='passport', max_length=50),
        ),
    ]
