# Generated by Django 2.0.9 on 2019-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190117_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_whitelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('none', 'None'), ('mobile_number', 'Mobile number'), ('country', 'Country'), ('photo', 'Photo')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('id_card', 'ID Card'), ('drive_license', 'Drive License')], default='passport', max_length=50),
        ),
    ]
