# Generated by Django 2.0.9 on 2019-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190117_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Is_whitelisted',
            new_name='is_whitelisted',
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.CharField(choices=[('photo', 'Photo'), ('country', 'Country'), ('none', 'None'), ('mobile_number', 'Mobile number')], default='none', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('id_card', 'ID Card'), ('drive_license', 'Drive License'), ('passport', 'Passport')], default='passport', max_length=50),
        ),
    ]
