
const actionTypes = {
    //USER ACTION
    USER_SAVE_PROFILE: "USER_SAVE_PROFILE",
    USER_LOG_IN: "USER_LOG_IN",
    USER_LOG_OUT: "USER_LOG_OUT",
    USER_SAVE_JWT: "USER_SAVE_JWT",
    USER_DELETE_JWT: "USER_DELETE_JWT",
    USER_SAVE_USERNAME: "USER_SAVE_USERNAME",
    USER_DELETE_USERNAME: "USER_DELETE_USERNAME",
    USER_SAVE_EMAIL: "USER_SAVE_EMAIL",
    USER_DELETE_EMAIL: "USER_DELETE_EMAIL",
    USER_SAVE_REFERRAL_QUERY: "USER_SAVE_REFERRAL_QUERY",
    USER_SAVE_REMEMBER_ME: "USER_SAVE_REMEMBER_ME",
    USER_SAVE_TEMP_KEY: "USER_SAVE_TEMP_KEY",

    //KYC ACTION
    KYC_SAVE_KYC: "KYC_SAVE_KYC",
    KYC_SAVE_KYC_COUNT: "KYC_SAVE_KYC_COUNT",

    //SPINNER ACTION
    SPINNER_SHOW_DEFAULT_SPINNER: "SPINNER_SHOW_DEFAULT_SPINNER",
    SPINNER_HIDE_DEFAULT_SPINNER: "SPINNER_HIDE_DEFAULT_SPINNER",

    //CONFIG ACTION
    CONFIG_SAVE_ICO_WALLET_LIST: "CONFIG_SAVE_ICO_WALLET_LIST",
    CONFIG_SAVE_CURRENT_ROUND: "CONFIG_SAVE_CURRENT_ROUND",
    CONFIG_SAVE_ROUND_LIST: "CONFIG_SAVE_ROUND_LIST",
    CONFIG_SAVE_WHITEPAPER: "CONFIG_SAVE_WHITEPAPER",
    CONFIG_SAVE_INVESTMENT_INFO: "CONFIG_SAVE_INVESTMENT_INFO",
    CONFIG_SAVE_ICO_FUND_AMOUNT: "CONFIG_SAVE_ICO_FUND_AMOUNT",
    CONFIG_SAVE_ROUND_SUPPLY_LIST: "CONFIG_SAVE_ROUND_SUPPLY_LIST",
    CONFIG_SAVE_ROUND_BONUS_LIST: "CONFIG_SAVE_ROUND_BONUS_LIST",
    CONFIG_SAVE_BG_IMAGE: "CONFIG_SAVE_BG_IMAGE",
    CONFIG_SAVE_REF_TOKEN_SALE: "CONFIG_SAVE_REF_TOKEN_SALE",
    CONFIG_SAVE_REF_ROADMAP: "CONFIG_SAVE_REF_ROADMAP",
    CONFIG_SAVE_REF_TEAM: "CONFIG_SAVE_REF_TEAM",
    CONFIG_SAVE_REF_PARTNER: "CONFIG_SAVE_REF_PARTNER",
    CONFIG_SAVE_REF_CONTACT: "CONFIG_SAVE_REF_CONTACT",
    CONFIG_SAVE_REF_WHATIS: "CONFIG_SAVE_REF_WHATIS",
    CONFIG_SAVE_HOME_LOCATION: "CONFIG_SAVE_HOME_LOCATION",
    CONFIG_SAVE_ICO_TRANSACTIONS: "CONFIG_SAVE_ICO_TRANSACTIONS",
    CONFIG_SAVE_INTERNAL_ICO_TRANSACTIONS: "CONFIG_SAVE_INTERNAL_ICO_TRANSACTIONS",

};
    
export default actionTypes;